---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik-system

resources:
  - manifests/namespace.yaml
  - flux/helm-repository.yaml
  - flux/helm-release.yaml

components:
  - ../../../components/common-kustomizeconfig
  - ../../.,/components/bitnami-repository
