apiVersion: v1
kind: Secret
metadata:
  name: gotify-default-user
stringData:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:ZhVBXEg=,iv:pPFBAGsmOHN/H2Aeu8hOtcrBrEv2K/edAJ9P+oIbwos=,tag:Lj9kF6V4noXoP1SPLO0a2Q==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:SsGYdDo6A23DrcpnSbm+iymWFORpDPMt,iv:i7a7ZXl3yiQWrSAOuLRFKr1tlHMxN8SyO5VmnW60eCw=,tag:tgZZKoA9Vkdcr48FbVPshw==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R2c4SklvNWNrZ3hRME1y
        dEdNYS9YUGNGM21JWkZRLytCd0VXSWFodFJrClFwazUrZGJJV1MxMHlXVDFucFYw
        bWY5ZmtZMUljUTI1d2F6d1ZLRjZVaVUKLS0tIEdCVzJLeFY0bVExY3hmQ0NBWXMy
        ZW9wbnNKU3FjMmpLYS9mTCs1aEYwbUUKWm+A0kQQ0Km5UpQjrG6kyD+B3IaCGrss
        KfnWpfSzOsXna82uhLRXeJM6W93BOG5EblBnt55Z3HDo2D+kJXzdoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T12:55:10Z"
  mac: ENC[AES256_GCM,data:BbGyYr868AkS86otaqsIFDpBqvJBF4IzfoffWAtSoGZ3HQ7de8FHZRD28EZkIAvLGRS0jG4DSNLAhgAKVKSYEyTc+7fNsDDayZ7RleOqqENp1aAsN4/DIdaDihjc5wYKBrbmiIIc750h4ueYysgv73g/FVmETDSR7y3K1JFfh2g=,iv:WpaFvWmJ7dXTnFfHyxDR2leFw25qmtMtLhRMXlQHmKo=,tag:wYjmx3f/X5CeVSXZ0nG80A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-restic-data
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:8XtRg6w1NFSWZ6F3NrCHtLF3KVz5PfsXC7yR0w==,iv:wPyLMPXR28XuqP2soQ+qBcoCikMWFD7mSHpJf6HBJbA=,tag:25DToMJLJoozVp8haZ8M4Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:pfY/oebAK/f9fBYDr9JqrnHO09TPr6Ed1/bDUdhakP0IOFfGdLH5P7pBV2XpTpXLJI4gX+0=,iv:uJWtiRMRAlIr12PJW/NzXiQ5OHMGACEio28vPBOGJSg=,tag:tTv8NYYV1bK/RzXxpHegEg==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:DqkuFd5Gp1kf+AXCbSPdgl7oakA=,iv:l3ARh/gE1hE2I9vKaUL2AYsniuQ92h/G5sYgPP7rYhg=,tag:9FXxPasYHhUY4JYGPLZoPQ==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:Rr1VVHRPXp4/AJIucVtp+udF5ozf1mzghmuD+wKmzLA87kEyQYhicbF88C2mMzThA5RNE/YIjp3cXS4=,iv:0hc7SEdpZBZ5lX+Qx1ZRBYdKfYy2wQQ8kdaCYPJV6Ec=,tag:TdKdKvAHNJVUiA6n1U1xSQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R2c4SklvNWNrZ3hRME1y
        dEdNYS9YUGNGM21JWkZRLytCd0VXSWFodFJrClFwazUrZGJJV1MxMHlXVDFucFYw
        bWY5ZmtZMUljUTI1d2F6d1ZLRjZVaVUKLS0tIEdCVzJLeFY0bVExY3hmQ0NBWXMy
        ZW9wbnNKU3FjMmpLYS9mTCs1aEYwbUUKWm+A0kQQ0Km5UpQjrG6kyD+B3IaCGrss
        KfnWpfSzOsXna82uhLRXeJM6W93BOG5EblBnt55Z3HDo2D+kJXzdoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T12:55:10Z"
  mac: ENC[AES256_GCM,data:BbGyYr868AkS86otaqsIFDpBqvJBF4IzfoffWAtSoGZ3HQ7de8FHZRD28EZkIAvLGRS0jG4DSNLAhgAKVKSYEyTc+7fNsDDayZ7RleOqqENp1aAsN4/DIdaDihjc5wYKBrbmiIIc750h4ueYysgv73g/FVmETDSR7y3K1JFfh2g=,iv:WpaFvWmJ7dXTnFfHyxDR2leFw25qmtMtLhRMXlQHmKo=,tag:wYjmx3f/X5CeVSXZ0nG80A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-user
stringData:
  username: ENC[AES256_GCM,data:lzgHPZo1,iv:Gj+krSXJzEOj5Y8xr3H/tsR8rP5vtLnPPliTpNbO4A0=,tag:p8tjKI8W7hivqGdfomiwQA==,type:str]
  password: ENC[AES256_GCM,data:nwvV8s2bOkYp+VzuWPSfvFlZZ+6cpQUo,iv:ZtQFIb7Y2lQfQNZuqVpwcu+R1xXCOcwomgHX1XM51o8=,tag:ECIx6yRMiA6yJCuMGHJ4PQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R2c4SklvNWNrZ3hRME1y
        dEdNYS9YUGNGM21JWkZRLytCd0VXSWFodFJrClFwazUrZGJJV1MxMHlXVDFucFYw
        bWY5ZmtZMUljUTI1d2F6d1ZLRjZVaVUKLS0tIEdCVzJLeFY0bVExY3hmQ0NBWXMy
        ZW9wbnNKU3FjMmpLYS9mTCs1aEYwbUUKWm+A0kQQ0Km5UpQjrG6kyD+B3IaCGrss
        KfnWpfSzOsXna82uhLRXeJM6W93BOG5EblBnt55Z3HDo2D+kJXzdoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T12:55:10Z"
  mac: ENC[AES256_GCM,data:BbGyYr868AkS86otaqsIFDpBqvJBF4IzfoffWAtSoGZ3HQ7de8FHZRD28EZkIAvLGRS0jG4DSNLAhgAKVKSYEyTc+7fNsDDayZ7RleOqqENp1aAsN4/DIdaDihjc5wYKBrbmiIIc750h4ueYysgv73g/FVmETDSR7y3K1JFfh2g=,iv:WpaFvWmJ7dXTnFfHyxDR2leFw25qmtMtLhRMXlQHmKo=,tag:wYjmx3f/X5CeVSXZ0nG80A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-connection
stringData:
  GOTIFY_DATABASE_CONNECTION: ENC[AES256_GCM,data:QvjZVGBLNq+5FawDUSVOBvgSvJrNONHPYz2l6JcPQ+27f1lSAM9WPkQxVqCeaH6Zn9FefzrzF2RWbMNZiQTq1XitIjC1upfcny56xUpFVNZB+gAGmLvZZnJexLsYnwn2kzZI0QUATt59,iv:pgr6Jtrlz+3oyFXW9CnP3MNJnODbnOIb6UwNkSdCT7Q=,tag:n4qCv+reRI9jRaaLJnBxKA==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4R2c4SklvNWNrZ3hRME1y
        dEdNYS9YUGNGM21JWkZRLytCd0VXSWFodFJrClFwazUrZGJJV1MxMHlXVDFucFYw
        bWY5ZmtZMUljUTI1d2F6d1ZLRjZVaVUKLS0tIEdCVzJLeFY0bVExY3hmQ0NBWXMy
        ZW9wbnNKU3FjMmpLYS9mTCs1aEYwbUUKWm+A0kQQ0Km5UpQjrG6kyD+B3IaCGrss
        KfnWpfSzOsXna82uhLRXeJM6W93BOG5EblBnt55Z3HDo2D+kJXzdoA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T12:55:10Z"
  mac: ENC[AES256_GCM,data:BbGyYr868AkS86otaqsIFDpBqvJBF4IzfoffWAtSoGZ3HQ7de8FHZRD28EZkIAvLGRS0jG4DSNLAhgAKVKSYEyTc+7fNsDDayZ7RleOqqENp1aAsN4/DIdaDihjc5wYKBrbmiIIc750h4ueYysgv73g/FVmETDSR7y3K1JFfh2g=,iv:WpaFvWmJ7dXTnFfHyxDR2leFw25qmtMtLhRMXlQHmKo=,tag:wYjmx3f/X5CeVSXZ0nG80A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
