apiVersion: v1
kind: Secret
metadata:
  name: gotify-default-user
stringData:
  GOTIFY_DEFAULTUSER_NAME: ENC[AES256_GCM,data:NHMw4QA=,iv:eelUVNX3OH7JMHATQ7xrwGf3MAPO++aZfzeItziFX48=,tag:R555XIMM++A3UzE2x/M2EA==,type:str]
  GOTIFY_DEFAULTUSER_PASS: ENC[AES256_GCM,data:8d8/Z9HQsJXkfCYvecEqkMIw/yAUO/+c,iv:3KjVKJIU8TVd8HW99QMDMgkd9xZqE5PDBSQZjtMmQns=,tag:kW9zde1XqPAWmetQRKXiIg==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-restic-data
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:/8DWQ0TyHIeKyQy4brYc29KohswKhQaDpHXyjA==,iv:FdLfLQhfVBcNjnqkmI13PVRd4D+Fl9poTOR6hEbPiBw=,tag:56OsM7UcLvrdPCM9qMkvUQ==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:vQI5IexLbo0sZRuf/GxcJxd72pNSIpXNRNT7uZMF1UfcVTNQVDRLYAzm1Lxh0GkcSTRjzDo=,iv:1+5oohLEhSbIOqLxyEMyzEU5P2fhd715tGXLXq32fc8=,tag:UwVMC6FmuVzANTbmWOxcfw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:ZlaYHos9efe6+MZbNKriWKalWYc=,iv:e+SvIQhlSUftx/HK21hpbTbllbYyp0JcvJ+B30G89fw=,tag:42tP/Mw7lESgfGOZ6UXwaw==,type:str]
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:L4MgoXCQ2KNbn+hUAwO03KtbwKKaCfD/loSwvfxhRzJS7WxlEQ65Mdw49vSxiaB3XvOXfvL/7UCy9zE=,iv:P6aotVr8wA1GNLiS5fYI8Rhgr4ofG10E1lXELw6Pxq4=,tag:JvVvC7YFB/cPYtlTNZOHgQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-user
stringData:
  username: ENC[AES256_GCM,data:ifuce4IU,iv:QhbDSjQWOQCI4Jfwpyi/45kq2YLWgXMTf8PoD5irLjY=,tag:EmN2sU59caTlfMDcFTxlMg==,type:str]
  password: ENC[AES256_GCM,data:tITojKg3TzEkkillTcSQT/bY//9lkJlF,iv:k7jD5M6DCBF8wjDkzbCLJuZkO7xEDLEJLN9RGROa/PY=,tag:h5jkr7kYvH+qxWx//JG/wg==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-custom-cnpg-connection
stringData:
  GOTIFY_DATABASE_CONNECTION: ENC[AES256_GCM,data:XQNS9fZCM8cuUohPnIfgnOC1W2hY2DrWaPd+5+qsiXS2LvA8lyNm71hNmKwBQST4bkM3AHNrwD0TgcR4FRgpxeT6zsNwnCYpcOJns7iCUPtLYrKNSJoWi09C13dIlJZfXveUzLTZB9EE,iv:8ZKAtTZfxO0rW0uL/XB6DQWBtWRQzUmSq1rmUm6TC30=,tag:bfnjKmTbQlkAPz8qelLKpA==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: gotify-alertmanager-bridge-default-token
stringData:
  GOTIFY_TOKEN: ENC[AES256_GCM,data:xxgv+PuCFobffobFyS8a,iv:7wf64LJggX18+BCFPfQdxT5uzbyRb6M6qfaLhR8Bvtw=,tag:uBaN+QRqlUU/Eq6lAQFlLA==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-gotify-joker9944
stringData:
  url: ENC[AES256_GCM,data:+kFI9WF5DCHVyST+NBstmq3SYaIMPrHIbaR/onx/0SJMouAoMuDNYa3wabaqBcsst+cU/uXv45dO/vmWTyZIV+gPqKhkYT45J8DUZ6X+RsfwjnJ8ul4yvg==,iv:3ltJ+TbFrGucy8lQ0wUUlQ4Hd2RW9dw7DIce0spITXg=,tag:E2AEEL4+vUEyTmmJikSVaQ==,type:str]
sops:
  age:
    - recipient: age1pee99j8wzwkgx98xcx7vqhj4ml2qh8farzanv07pmhrlr9x3uyxqp6dw8h
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWmpJVWVHeHJRV1FRYVZy
        eGg0ZjJhRXg3V2NJVmRPbE9lM3RrV21kcGlnCms2TWVWRnZ2bjRLMFE2ZXhGTXM1
        dURyWXJFOE9TYnljTUNOS0NGOVhrVWcKLS0tIEVyK3lWZS8zck9DUVo4Unh1S1lJ
        aTRPdTdLdlJrNkVWcEhGQ29YZ3paNzgKnXQufonxTiGg23lJTX01wzej/E7I677C
        uswit35lT30Acn5tCOmgyc4SLmXrCKAB7TbYzSZhcxXrFEEa2Nj2xA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-23T19:14:17Z"
  mac: ENC[AES256_GCM,data:oNuPE6639xgcYxQLsC+oroEfSNCJiFeTfS2vJUF8S5gC5/ugyvtN5J1ceftsWlowLHkEfz8T0wUnZe6yiOHOrwxrC9SXxNwks5hCS0+KYxzJSFIdZkwKIvUj29ATUW7oazwA8Hfu09JRLciieIraXnWVJWZrBTGgx5A4u3oYzBw=,iv:9exRnkv4MVapDKG9aKLmdzlzjguK9/aahVegnE2ekiA=,tag:4rTRtw0FsfMIA7qoNIWfuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
