apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gotify

resources:
  - manifests/namespace.yaml
  - manifests/secret.yaml
  - flux/helm-release.yaml

components:
  - ../../../components/common-kustomizeconfig
  - ../../../components/common-middlewares
  - ../../../components/bjw-s-helm-repository
